### ISSUE TITLE
Actions aren't really attributes in Caves of Zircon, they're a code smell which means something may be missing

### ISSUE THREAD

**Issue by BobG1983** [Hexworks/amethyst#3]
Caves of Zircon has an attribute called Actions which is a command container, which is basically a special case of 

if(hasAttribute)
  dispatchCommandOnOtherEntity

Its a useful construct, but it feels like its a code smell and something is missing.

Actions could be hoisted up to be equivalent to facets, behaviors etc. but then you could only trigger them all. So having different triggers (bump vs shoot vs eat for example) wouldn’t work. Is there some missing concept?

Or is this the least worst idea?

**Comment by RantingBob** [comment]
Actions could be hoisted up to be equivalent to facets, behaviors etc. but then you could only trigger them all. So having different triggers (bump vs shoot vs eat for example) wouldn’t work. Is there some missing concept?

**Comment by BobG1983** [comment]
My gut is that this may change once we have single command facets and global systems solved

**Comment by bruce-forte** [comment]
I agree. I think I'll draw a diagram with all these things, and write some examples just to give ourselves some ammunition for thinking about this.

**Comment by bruce-forte** [comment]
You were right, the `Facet` composition is a good solution to create a command dispatcher and we can just send specific `Command`s to an `Entity` when we want to try its actions so this:

```kotlin
result = entity.tryActionsOn(context, block.occupier.get())
```

we can do 

```kotlin
result = entity.executeCommand(TryAction(context, block.occupier.get())
```
